import { CCTVCamera, SafetyZone, ThreatReport, UserProfile, SystemSettings, SOSEvent } from '@/types';

// Preset landmark locations for easy testing
export const CITY_CENTER = { lat: 12.9716, lng: 77.5946 }; // Bangalore City Center coordinates (interchangeable)

export const POPULAR_LOCATIONS = [
  { name: 'Central Transit Hub & Metro', lat: 12.9767, lng: 77.5713, address: 'Majestic Station Rd' },
  { name: 'City Central Park (Cubbon)', lat: 12.9738, lng: 77.5907, address: 'Kasturba Road' },
  { name: 'Tech Park Boulevard', lat: 12.9569, lng: 77.7011, address: 'Outer Ring Road, Marathahalli' },
  { name: 'University Campus North Gate', lat: 12.9344, lng: 77.6060, address: 'Hosur Main Road' },
  { name: 'Downtown Commercial Plaza', lat: 12.9784, lng: 77.6067, address: 'MG Road Promenade' },
  { name: 'General Memorial Hospital', lat: 12.9652, lng: 77.5985, address: 'Victoria Hospital Compound' },
  { name: 'Greenwood Residential Sector', lat: 12.9830, lng: 77.6380, address: 'Indiranagar 100ft Road' },
  { name: 'Riverwalk Esplanade', lat: 12.9250, lng: 77.5890, address: 'Jayanagar 4th Block' },
];

export const INITIAL_CAMERAS: CCTVCamera[] = [
  {
    id: 'cam-01',
    cameraCode: 'CCTV-BLR-101',
    name: 'MG Road Junction North',
    location: { lat: 12.9752, lng: 77.6074 },
    address: 'MG Road & Brigade Rd Crossing',
    streamUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    fieldOfViewAngle: 120,
    updatedAt: new Date().toISOString(),
    lastAnalysis: {
      id: 'an-01',
      cameraId: 'cam-01',
      cameraCode: 'CCTV-BLR-101',
      timestamp: new Date().toISOString(),
      humanCount: 42,
      crowdDensityPercent: 48,
      lightingScore: 92,
      anomalyDetected: false,
      anomalyType: 'none',
      safetyScoreContribution: 94,
      analyzedInputType: 'video',
      confidenceScore: 0.96,
      notes: 'Active pedestrian flow, bright LED street lighting, clear vision.',
    },
  },
  {
    id: 'cam-02',
    cameraCode: 'CCTV-BLR-102',
    name: 'Cubbon Park South Promenade',
    location: { lat: 12.9721, lng: 77.5925 },
    address: 'Kasturba Road Outer Gate',
    streamUrl: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    fieldOfViewAngle: 90,
    updatedAt: new Date().toISOString(),
    lastAnalysis: {
      id: 'an-02',
      cameraId: 'cam-02',
      cameraCode: 'CCTV-BLR-102',
      timestamp: new Date().toISOString(),
      humanCount: 18,
      crowdDensityPercent: 25,
      lightingScore: 78,
      anomalyDetected: false,
      anomalyType: 'none',
      safetyScoreContribution: 88,
      analyzedInputType: 'image',
      confidenceScore: 0.94,
      notes: 'Calm evening walkers, adequate lighting along perimeter walkway.',
    },
  },
  {
    id: 'cam-03',
    cameraCode: 'CCTV-BLR-103',
    name: 'Alleyway 4 Behind Central Arcade',
    location: { lat: 12.9735, lng: 77.6040 },
    address: 'Rest House Road Alley',
    streamUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    fieldOfViewAngle: 75,
    updatedAt: new Date().toISOString(),
    lastAnalysis: {
      id: 'an-03',
      cameraId: 'cam-03',
      cameraCode: 'CCTV-BLR-103',
      timestamp: new Date().toISOString(),
      humanCount: 2,
      crowdDensityPercent: 6,
      lightingScore: 35,
      anomalyDetected: true,
      anomalyType: 'darkness',
      safetyScoreContribution: 38,
      analyzedInputType: 'video',
      confidenceScore: 0.89,
      notes: 'Subdued lighting detected, low foot traffic, flagged as high vigilance sector.',
    },
  },
  {
    id: 'cam-04',
    cameraCode: 'CCTV-BLR-104',
    name: 'Hospital Emergency Entrance Gate',
    location: { lat: 12.9660, lng: 77.5990 },
    address: 'Victoria Hospital Circle',
    streamUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    fieldOfViewAngle: 140,
    updatedAt: new Date().toISOString(),
    lastAnalysis: {
      id: 'an-04',
      cameraId: 'cam-04',
      cameraCode: 'CCTV-BLR-104',
      timestamp: new Date().toISOString(),
      humanCount: 29,
      crowdDensityPercent: 55,
      lightingScore: 95,
      anomalyDetected: false,
      anomalyType: 'none',
      safetyScoreContribution: 96,
      analyzedInputType: 'video',
      confidenceScore: 0.98,
      notes: 'High security area, emergency responders on standby, optimal flood illumination.',
    },
  },
  {
    id: 'cam-05',
    cameraCode: 'CCTV-BLR-105',
    name: 'Underpass Walkway West',
    location: { lat: 12.9775, lng: 77.5740 },
    address: 'Majestic Subway Corridor B',
    streamUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
    status: 'online',
    fieldOfViewAngle: 110,
    updatedAt: new Date().toISOString(),
    lastAnalysis: {
      id: 'an-05',
      cameraId: 'cam-05',
      cameraCode: 'CCTV-BLR-105',
      timestamp: new Date().toISOString(),
      humanCount: 14,
      crowdDensityPercent: 32,
      lightingScore: 68,
      anomalyDetected: false,
      anomalyType: 'none',
      safetyScoreContribution: 79,
      analyzedInputType: 'video',
      confidenceScore: 0.91,
      notes: 'Moderate commuter movement, municipal surveillance active.',
    },
  },
];

export const INITIAL_SAFETY_ZONES: SafetyZone[] = [
  {
    id: 'zone-01',
    name: 'Brigade-MG Monitored Safe Corridor',
    type: 'safe_corridor',
    baseScore: 95,
    center: { lat: 12.9750, lng: 77.6080 },
    radiusMeters: 650,
    description: 'Designated high-security safe corridor with continuous police foot patrol and LED illumination.',
    active: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-02',
    name: 'Victoria Medical Security Perimeter',
    type: 'police_patrol_sector',
    baseScore: 92,
    center: { lat: 12.9655, lng: 77.5992 },
    radiusMeters: 500,
    description: '24/7 guarded hospital zone with immediate emergency medical access.',
    active: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-03',
    name: 'Railway Goods Yard Fringe',
    type: 'caution_zone',
    baseScore: 42,
    center: { lat: 12.9790, lng: 77.5680 },
    radiusMeters: 550,
    description: 'Industrial transition zone with sparse lighting and limited pedestrian visibility after 21:00.',
    active: true,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zone-04',
    name: 'Old Canal Desolate Stretch',
    type: 'high_risk_zone',
    baseScore: 28,
    center: { lat: 12.9690, lng: 77.5810 },
    radiusMeters: 400,
    description: 'Unlit pedestrian trail along dry canal bed. Multiple unverified incidents reported.',
    active: true,
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_THREAT_REPORTS: ThreatReport[] = [
  {
    id: 'rep-01',
    userId: 'usr-demo-01',
    userName: 'Aisha Sharma',
    category: 'poor_lighting',
    severity: 'high',
    description: 'Three consecutive street lamps broken between 4th and 5th cross. Pitch dark corridor.',
    latitude: 12.9740,
    longitude: 77.6025,
    address: 'Near St. Patrick Church Rd',
    imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?auto=format&fit=crop&w=600&q=80',
    status: 'verified',
    reviewedBy: 'admin@safecity.org',
    reviewedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    verificationNotes: 'Verified by patrol officer #42. Municipal lighting crew dispatched.',
    upvotes: 14,
    createdAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 'rep-02',
    userId: 'usr-demo-02',
    userName: 'Rahul Nair',
    category: 'suspicious_activity',
    severity: 'moderate',
    description: 'Group loitering near vacant construction site, harassing solitary commuters.',
    latitude: 12.9695,
    longitude: 77.5830,
    address: 'Old Canal Rd Crossing',
    status: 'verified',
    reviewedBy: 'admin@safecity.org',
    reviewedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    verificationNotes: 'Police patrol car rerouted to this sector.',
    upvotes: 8,
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'rep-03',
    userId: 'usr-demo-03',
    userName: 'Priya Sundaram',
    category: 'blocked_route',
    severity: 'low',
    description: 'Sidewalk excavation and construction debris forcing pedestrians onto vehicular road.',
    latitude: 12.9760,
    longitude: 77.5950,
    address: 'Near Cubbon Gate entrance',
    status: 'pending',
    upvotes: 3,
    createdAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
  },
  {
    id: 'rep-04',
    userId: 'usr-demo-04',
    userName: 'Vikram Joshi',
    category: 'wildlife_hazard',
    severity: 'moderate',
    description: 'Aggressive pack of stray dogs barking at cyclists and late night walkers.',
    latitude: 12.9810,
    longitude: 77.6210,
    address: 'Indiranagar 1st Stage',
    status: 'under_review',
    upvotes: 5,
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
];

export const INITIAL_SYSTEM_SETTINGS: SystemSettings = {
  engineMode: 'hybrid',
  aiModelProvider: 'google_gemini',
  aiModelName: 'gemini-1.5-flash',
  emergencyNumbers: {
    police: '112',
    ambulance: '108',
    womenHelpline: '1091',
    fireRescue: '101',
  },
  sosAutoDial: true,
  sosBroadcastAdmin: true,
  verifiedReportsWeight: 25,
  cctvFreshnessTtlMinutes: 15,
  maintenanceMode: false,
  updatedAt: new Date().toISOString(),
};

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'admin-001',
    email: 'admin@safecity.org',
    displayName: 'Chief Safety Administrator',
    phoneNumber: '+1-555-0199',
    role: 'admin',
    status: 'active',
    emergencyContacts: [
      { id: 'ec-1', name: 'Emergency Command Center', phone: '+1-555-0911', relationship: 'Official Dispatch', notifyOnSOS: true }
    ],
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'mod-001',
    email: 'moderator@safecity.org',
    displayName: 'Dispatcher Sara',
    phoneNumber: '+1-555-0188',
    role: 'safety_moderator',
    status: 'active',
    emergencyContacts: [],
    createdAt: new Date(Date.now() - 86400000 * 15).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'user-001',
    email: 'user@safecity.org',
    displayName: 'Ananya Roy',
    phoneNumber: '+1-555-0122',
    role: 'user',
    status: 'active',
    emergencyContacts: [
      { id: 'ec-2', name: 'Rohan Roy (Brother)', phone: '+1-555-0144', relationship: 'Brother', notifyOnSOS: true },
      { id: 'ec-3', name: 'Meera Roy (Mother)', phone: '+1-555-0166', relationship: 'Mother', notifyOnSOS: true }
    ],
    createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_SOS_EVENTS: SOSEvent[] = [
  {
    id: 'sos-01',
    userId: 'user-001',
    userName: 'Ananya Roy',
    userPhone: '+1-555-0122',
    latitude: 12.9735,
    longitude: 77.6040,
    accuracyMeters: 4.8,
    status: 'police_dispatched',
    mapLink: 'https://maps.google.com/?q=12.9735,77.6040',
    notifiedContacts: ['Rohan Roy (Brother): +1-555-0144', 'Meera Roy (Mother): +1-555-0166'],
    responderNotes: 'Nearest patrol cruiser Alpha-4 dispatched. Arrival in 2 mins.',
    dispatchedTo: 'Metro Police Sector 3',
    timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
  },
];
